task_ABSOLUTELY_00001:
  video_path: "/date/zhuyy/MuseTalk/data/lrw/lipread_mp4/ABSOLUTELY/test/ABSOLUTELY_00001.mp4"
  audio_path: "/date/zhuyy/MuseTalk/results/ABSOLUTELY_00001.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 8
  guide_scale: 0.25
