# task_1:
#   video_path: "./results/test25_example.mp4"
#   audio_path: "./new_train_data/audios/test25.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 1
#   guide_scale: 0.0

task_2:
  video_path: "./results/test25"
  audio_path: "./new_train_data/audios/test25.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 1
  guide_scale: 0.0