task_1:
  video_path: "./results/test3_example.mp4"
  audio_path: "./new_train_data/audios/test3.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 1
  guide_scale: 0

# task_2:
#   video_path: "./results/test3"
#   audio_path: "./new_train_data/audios/test3.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 4
#   guide_scale: 0.25

# task_3:
#   video_path: "./results/test3"
#   audio_path: "./new_train_data/audios/test3.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 8
#   guide_scale: 0.25
