task_1:
  video_path: "./results/test25_test27"
  audio_path: "./new_train_data/audios/ACROSS_00961.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 1
  guide_scale: 0.25

# task_2:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 1
#   guide_scale: 0.5

# task_3:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 1
#   guide_scale: 0.75

# task_4:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 1
#   guide_scale: 1.0


# task_5:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 2
#   guide_scale: 0.25



# task_6:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 2
#   guide_scale: 0.5

# task_7:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 2
#   guide_scale: 0.75

# task_8:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 2
#   guide_scale: 1.0

# task_9:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 4
#   guide_scale: 0.25

# task_10:
#   video_path: "./results/test25"
#   audio_path: "./new_train_data/audios/test27.wav"
#   crop_path: ""
#   face_embs_path: ""
#   bbox_shift: 0
#   n_cond: 4
#   guide_scale: 0.5



task_11:
  video_path: "./results/test25"
  audio_path: "./new_train_data/audios/test27.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 4
  guide_scale: 0.75

task_12:
  video_path: "./results/test25"
  audio_path: "./new_train_data/audios/test27.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 4
  guide_scale: 1.0


task_17:
  video_path: "./results/test25"
  audio_path: "./new_train_data/audios/test27.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 8
  guide_scale: 0.25

task_18:
  video_path: "./results/test25"
  audio_path: "./new_train_data/audios/test27.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 8
  guide_scale: 0.5

task_19:
  video_path: "./results/test25"
  audio_path: "./new_train_data/audios/test27.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 8
  guide_scale: 0.75

task_20:
  video_path: "./results/test25"
  audio_path: "./new_train_data/audios/test27.wav"
  crop_path: ""
  face_embs_path: ""
  bbox_shift: 0
  n_cond: 8
  guide_scale: 1.0