test25_0:
  gt_video_path: "./new_train_data/images/ABUSE_00456"
  generated_video_path: "./results/ABUSE_00456_ABUSE_00456_v_adapter_0.0_3_adapter_False_0.0.mp4"
  generated_cropped: True
  gt_cropped: False
  result_save_path: "./evaluate_results/ABUSE_00456_3_0"

test25_25:
  gt_video_path: "./new_train_data/images/ABUSE_00456"
  generated_video_path: "./results/ABUSE_00456_ABUSE_00456_v_adapter_0.25_3_adapter_False_0.25.mp4"
  generated_cropped: True
  gt_cropped: False
  result_save_path: "./evaluate_results/ABUSE_00456_3_0.25"

test25_5:
  gt_video_path: "./new_train_data/images/ABUSE_00456"
  generated_video_path: "./results/ABUSE_00456_ABUSE_00456_v_adapter_0.5_3_adapter_False_0.5.mp4"
  generated_cropped: True
  gt_cropped: False
  result_save_path: "./evaluate_results/ABUSE_00456_3_0.5"

test25_75:
  gt_video_path: "./new_train_data/images/ABUSE_00456"
  generated_video_path: "./results/ABUSE_00456_ABUSE_00456_v_adapter_0.75_3_adapter_False_0.75.mp4"
  generated_cropped: True
  gt_cropped: False
  result_save_path: "./evaluate_results/ABUSE_00456_3_0.75"

test25_1:
  gt_video_path: "./new_train_data/images/ABUSE_00456"
  generated_video_path: "./results/ABUSE_00456_ABUSE_00456_v_adapter_1.0_3_adapter_False_1.0.mp4"
  generated_cropped: True
  gt_cropped: False
  result_save_path: "./evaluate_results/ABUSE_00456_3_1.0"

test26_25:
  gt_video_path: "./new_train_data/images/ABUSE_00456"
  generated_video_path: "./results/ABUSE_00456_ABUSE_00456_v_adapter_0.25_5_adapter_False_0.25.mp4"
  generated_cropped: True
  gt_cropped: False
  result_save_path: "./evaluate_results/ABUSE_00456_5_0.25"