test1:
  gt_video_path: "./new_train_data/images/ACROSS_00961"
  generated_video_path: "./results/ACROSS_00961_ACROSS_00961_v_adapter_0_5_1/crop_ACROSS_00961_ACROSS_00961_v_adapter_0_5_1"
  generated_cropped: False
  gt_cropped: False
  result_save_path: "./evaluate_results/ACROSS_00961_ACROSS_00961_v_adapter_0_5_1"

test2:
  gt_video_path: "./new_train_data/images/ACROSS_00961"
  generated_video_path: "./results/ACROSS_00961_ACROSS_00961_v_adapter_0_5_2/crop_ACROSS_00961_ACROSS_00961_v_adapter_0_5_2"
  generated_cropped: False
  gt_cropped: False
  result_save_path: "./evaluate_results/ACROSS_00961_ACROSS_00961_v_adapter_0_5_2"

test3:
  gt_video_path: "./new_train_data/images/ACROSS_00961"
  generated_video_path: "./results/ACROSS_00961_ACROSS_00961_v_adapter_0_5_4/crop_ACROSS_00961_ACROSS_00961_v_adapter_0_5_4"
  generated_cropped: False
  gt_cropped: False
  result_save_path: "./evaluate_results/ACROSS_00961_ACROSS_00961_v_adapter_0_5_4"


test4:
  gt_video_path: "./new_train_data/images/ACROSS_00961"
  generated_video_path: "./results/ACROSS_00961_ACROSS_00961_v_adapter_0_5_8/crop_ACROSS_00961_ACROSS_00961_v_adapter_0_5_8"
  generated_cropped: False
  gt_cropped: False
  result_save_path: "./evaluate_results/ACROSS_00961_ACROSS_00961_v_adapter_0_5_8"

